### ISSUE TITLE
Support for firefox

### ISSUE THREAD

**Issue by seif** [IbrahimMohammed47/boycott-z#1]
Thanks for your work. I use firefox and wanted to get this working.

Sadly it looks like the firefox support for manifestv3 background service isn't implemented and instead needed to use the scripts, which essentially means having to have 2 different manifest files.

I don't really have experience with publishing addons/plugins. Do you have a preference as to how these are published? I forked the project and a [minimal change](https://github.com/seif/boycott-z/commit/eeed8ed7ae01805e91f1906dbdd8696e0563889e) to the manifest got it working in 'web-ext run' without any modification the code.

Do you have a preference about how to handle this? Ideally it would be some sort of github action that will bundle and publish to the firefox/chrome stores. Simplest I can think of is a manifest.firefox.json and a manifest.chrome.json with 2 builds that use the relevant manifest for each platform. Quick search showed that there are some libraries/frameworks that help with this.

Let me know your thoughts.

**Comment by IbrahimMohammed47** [comment]
@seif 
Glad you liked it, Seif. I have no experience with firefox plugins and in fact this is the 1st extension I've ever built. Since I was planning to make a CI pipeline to publish the extension to chrome web store, I think adding a build phase for that reason makes sense.. so yeah, Having 2 manifests is the way to go. 

Feel free to PR this change(the 2 manifest files + a small bash script or build tool that builds into 2 folders: firefox-build and chrome-build) and later we can integrate this to a CI pipeline that builds then publishes to both browsers, what's important is that we can easily build with one command while both: developing and publishing(from CI file). 

If you think this can be done in a different way, let me know.. I will look more into this end of this end of week Insha'Allah.
