### ISSUE TITLE
Warning not shown for websites with different tld

### ISSUE THREAD

**Issue by seif** [IbrahimMohammed47/boycott-z#22]
Noticed that the warning is not shown for kayak.co.uk but when checking opentable.com it does show. Even though they are both in the same group (booking).

Looks like the issue is related to the tld, for example if I go to www.opentable.com it works however www.opentable.co.uk it doesn't.

**Comment by IbrahimMohammed47** [comment]
Yes this is on purpose.. companies are identified with their full domain name.
Because there are many cases where companies share same name but have different tlds.. in that case we don't want to give false alarms.
But for the case you're concerned about, we can just add more records for the same company but with its different tlds.

**Comment by seif** [comment]
"Because there are many cases where companies share same name but have different tlds.. in that case we don't want to give false alarms." that should be illegal :) I've not seen a company allow another company to use their name just under a different tld. However, I see your point :) i can think of is Aldi, where Aldi in europe is on boycott but Aldi in UK is not IIRC.
